## https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "poetry"
    - run: poetry install --sync
    - run: poetry run pytest
    - run: poetry build
